//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.11.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Client
{
    #pragma warning disable // Disable all warnings

    
}